services:
  facade-service:
    build: ./facade-service
    ports:
      - "8000:8000"
    depends_on:
      - logging-service-1
      - logging-service-2
      - logging-service-3
      - messages-service-1
      - messages-service-2
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
      - KAFKA_TOPIC=messages-topic
    networks:
      - hazelcast-network
      - kafka-network

  logging-service-1:
    build: ./logging-service
    ports:
      - "8001:8001"
    environment:
      - HAZELCAST_CLUSTER_NAME=dev
      - HAZELCAST_CLUSTER_MEMBERS=hazelcast1, hazelcast2, hazelcast3
    networks:
      - hazelcast-network
    depends_on:
      - hazelcast1

  logging-service-2:
    build: ./logging-service
    ports:
      - "8002:8001"
    environment:
      - HAZELCAST_CLUSTER_NAME=dev
      - HAZELCAST_CLUSTER_MEMBERS=hazelcast1, hazelcast2, hazelcast3
    networks:
      - hazelcast-network
    depends_on:
      - hazelcast2

  logging-service-3:
    build: ./logging-service
    ports:
      - "8003:8001"
    environment:
      - HAZELCAST_CLUSTER_NAME=dev
      - HAZELCAST_CLUSTER_MEMBERS=hazelcast1, hazelcast2, hazelcast3
    networks:
      - hazelcast-network
    depends_on:
      - hazelcast3

  messages-service-1:
    build: ./messages-service
    ports:
      - "8004:8004"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
      - KAFKA_TOPIC=messages-topic
      - SERVICE_ID=1
    networks:
      - kafka-network
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3

  messages-service-2:
    build: ./messages-service
    ports:
      - "8005:8004"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
      - KAFKA_TOPIC=messages-topic
      - SERVICE_ID=2
    networks:
      - kafka-network
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3

  hazelcast1:
    image: hazelcast/hazelcast:latest
    environment:
      - HAZELCAST_CLUSTER_NAME=dev
    ports:
      - "5701:5701"
    networks:
      - hazelcast-network

  hazelcast2:
    image: hazelcast/hazelcast:latest
    environment:
      - HAZELCAST_CLUSTER_NAME=dev
    ports:
      - "5702:5701"
    networks:
      - hazelcast-network

  hazelcast3:
    image: hazelcast/hazelcast:latest
    environment:
      - HAZELCAST_CLUSTER_NAME=dev
    ports:
      - "5703:5701"
    networks:
      - hazelcast-network

  management-center:
    image: hazelcast/management-center:latest
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast1,hazelcast2,hazelcast3
    ports:
      - "8080:8080"
    networks:
      - hazelcast-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  kafka-broker-1:
    image: apache/kafka:latest
    container_name: kafka-broker-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - kafka-network

  kafka-broker-2:
    image: apache/kafka:latest
    container_name: kafka-broker-2
    ports:
      - "9094:9092"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - kafka-network

  kafka-broker-3:
    image: apache/kafka:latest
    container_name: kafka-broker-3
    ports:
      - "9096:9092"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - kafka-network

networks:
  hazelcast-network:
    name: hazelcast-network
  kafka-network:
    name: kafka-network
