services:
  facade-service:
    build: ./facade-service
    ports:
      - "8000:8000"
    depends_on:
      - logging-service
      - messages-service

  logging-service:
    build: ./logging-service
    ports:
      - "8001:8001"

  messages-service:
    build: ./messages-service
    ports:
      - "8002:8002"